<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE menu [
<!ELEMENT menu (item*)>
<!ELEMENT item (item*)>
<!ATTLIST item label CDATA #REQUIRED>
<!ATTLIST item href CDATA #IMPLIED>
<!ATTLIST item target CDATA #IMPLIED>
<!ATTLIST item image CDATA #IMPLIED>
]>
<!-- 
/*
 * @author ggsddu
 * @url http://ggsddu.org/js-treemenu/
 * @email ggsddu.org@gmail.com
 */
-->
<menu>
	<item  label="中国" href="javascript:foo('嗨，你好！')" target="_self">
		<item  label="北京市" href="javascript:foo('嗨，你好！')" target="_self">
			<item  label="朝阳区" href="javascript:foo('嗨，你好！')" target="_self">
			</item>
			<item  label="丰台区" href="javascript:foo('嗨，你好！')" target="_self">
			</item>
		</item>
		<item  label="上海市" href="javascript:foo('嗨，你好！')" target="_self">
			<item  label="黄浦区" href="javascript:foo('嗨，你好！')" target="_self">
			</item>
			<item  label="闵行区" href="javascript:foo('嗨，你好！')" target="_self">
			</item>
		</item>
		<item  label="天津市" href="javascript:foo('嗨，你好！')" target="_self">
		</item>
		<item  label="重庆市" href="javascript:foo('嗨，你好！')" target="_self">
		</item>
		<item  label="黑龙江省" href="javascript:foo('嗨，你好！')" target="_self">
			<item  label="哈尔滨" href="javascript:foo('嗨，你好！')" target="_self">
			</item>
			<item  label="齐齐哈尔" href="javascript:foo('嗨，你好！')" target="_self">
			</item>
		</item>
		<item  label="吉林省" href="javascript:foo('嗨，你好！')" target="_self">
		</item>
		<item  label="辽宁省" href="javascript:foo('嗨，你好！')" target="_self">
		</item>
		<item  label="河北省" href="javascript:foo('嗨，你好！')" target="_self">
		</item>
		<item  label="山东省" href="javascript:foo('嗨，你好！')" target="_self">
		</item>
		<item  label="山西省" href="javascript:foo('嗨，你好！')" target="_self">
		</item>
		<item  label="河南省" href="javascript:foo('嗨，你好！')" target="_self">
		</item>
		<item  label="江苏省" href="javascript:foo('嗨，你好！')" target="_self">
		</item>
		<item  label="上海省" href="javascript:foo('嗨，你好！')" target="_self">
		</item>
		<item  label="浙江省" href="javascript:foo('嗨，你好！')" target="_self">
		</item>
		<item  label="福建省" href="javascript:foo('嗨，你好！')" target="_self">
		</item>
		<item  label="安徽省" href="javascript:foo('嗨，你好！')" target="_self">
		</item>
		<item  label="广东省" href="javascript:foo('嗨，你好！')" target="_self">
		</item>
		<item  label="广西壮族自治区" href="javascript:foo('嗨，你好！')" target="_self">
		</item>
		<item  label="江西省" href="javascript:foo('嗨，你好！')" target="_self">
		</item>
		<item  label="湖北省" href="javascript:foo('嗨，你好！')" target="_self">
		</item>
		<item  label="湖南省" href="javascript:foo('嗨，你好！')" target="_self">
		</item>
		<item  label="云南省" href="javascript:foo('嗨，你好！')" target="_self">
		</item>
		<item  label="贵州省" href="javascript:foo('嗨，你好！')" target="_self">
		</item>
		<item  label="四川省" href="javascript:foo('嗨，你好！')" target="_self">
		</item>
		<item  label="西藏自治区" href="javascript:foo('嗨，你好！')" target="_self">
		</item>
		<item  label="青海省" href="javascript:foo('嗨，你好！')" target="_self">
		</item>
		<item  label="新疆维吾尔自治区" href="javascript:foo('嗨，你好！')" target="_self">
		</item>
		<item  label="宁夏回族自治区" href="javascript:foo('嗨，你好！')" target="_self">
		</item>
		<item  label="甘肃省" href="javascript:foo('嗨，你好！')" target="_self">
		</item>
		<item  label="陕西省" href="javascript:foo('嗨，你好！')" target="_self">
		</item>
		<item  label="内蒙古自治区" href="javascript:foo('嗨，你好！')" target="_self">
		</item>
		<item  label="海南省" href="javascript:foo('嗨，你好！')" target="_self">
		</item>
		<item  label="台湾省" href="javascript:foo('嗨，你好！')" target="_self">
		</item>
	</item>
	<item  label="美国" href="javascript:foo('嗨，你好！')" target="_self">
		<item  label="纽约" href="javascript:foo('嗨，你好！')" target="_self">
		</item>
		<item  label="华盛顿" href="javascript:foo('嗨，你好！')" target="_self">
		</item>
		<item  label="洛杉矶" href="javascript:foo('嗨，你好！')" target="_self">
		</item>
		<item  label="旧金山" href="javascript:foo('嗨，你好！')" target="_self">
		</item>
	</item>
</menu>
